# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='n_user/avatar/defaultuser.png', upload_to='n_users/avatar/')),
            ],
        ),
        migrations.CreateModel(
            name='ONGLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natural_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naturalUser.NaturalUser')),
            ],
        ),
    ]
