# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 04:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ong', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('naturalUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onglike',
            name='ong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ong.ONG'),
        ),
        migrations.AddField(
            model_name='naturaluser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
