# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0003_auto_20171121_0003'),
        ('naturalUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ONGLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='naturaluser',
            name='avatar',
            field=models.ImageField(default='n_users/avatar/defaultuser.png', upload_to='n_users/avatar/'),
        ),
        migrations.AddField(
            model_name='onglike',
            name='natural_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naturalUser.NaturalUser'),
        ),
        migrations.AddField(
            model_name='onglike',
            name='ong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ong.ONG'),
        ),
    ]
