# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 03:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ong', '0002_ong_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onguser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='onguser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='ong',
            name='directions',
        ),
        migrations.RemoveField(
            model_name='ong',
            name='position',
        ),
        migrations.RemoveField(
            model_name='onguser',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='ong',
            name='avatar',
            field=models.ImageField(default='n_users/avatar/defaultuser.png', upload_to='ong/avatar/'),
        ),
        migrations.AddField(
            model_name='ong',
            name='favourites',
            field=models.IntegerField(default=0),
        ),


    ]
