# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0003_auto_20171121_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='onguser',
            name='id',
            field=models.AutoField(auto_created=True, default='key', serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
