# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 22:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_auto_20171023_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 22, 24, 35, 247308)),
        ),
    ]
