# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 03:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0008_auto_20171120_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 3, 0, 48, 198191, tzinfo=utc)),
        ),
    ]
