# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0010_auto_20171120_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
