# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0013_auto_20171120_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='case',
            field=models.SmallIntegerField(choices=[(1, 'Abandono en la calle'), (2, 'Exposicion a temperaturas<br>extremas'), (3, 'Falta de agua'), (4, 'Falta de comida'), (5, 'Violencia'), (6, 'Venta ambulante')]),
        ),
    ]
