# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0014_auto_20171120_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='lng',
            field=models.DecimalField(decimal_places=10, max_digits=13, null=True),
        ),
    ]
